name: Update Main Version Tag
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target_tag:
        description: The target tag
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v1

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2

    - name: Git config
      run: |
        git config user.name GitHub Action
        git config user.email action@github.com

    - name: Tag new target
      run: git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}

    - name: Push new tag
      run: git push origin ${{ github.event.inputs.major_version }} --force